#cs3350 Lab4 prog1
# to compile your project, type make and press enter

all: lab4

lab4: lab4.cpp
	g++ lab4.cpp -I /opt/x11/include -L /usr/X11/lib -Wall -o -lab4  -lGL -lGLU -lm

clean:
	rm -f lab4
	rm -f *.o
